"""Per-video directory layout, creation, cleaning, and mask-cache detection."""

from __future__ import annotations

import shutil
from dataclasses import dataclass
from pathlib import Path

from ..config import MaskCacheConfig, PathsConfig
from ..utils.logging import get_logger
from .images import IMAGE_SUFFIXES, list_frames

log = get_logger(__name__)


@dataclass
class RunPaths:
    """The four directories one video's run reads from and writes to."""

    video_name: str
    frames_dir: Path
    """Source TIFF frames. Never deleted when it lives under ``input_dir``."""

    unet_masks_dir: Path
    filtered_masks_dir: Path
    results_dir: Path
    frames_are_temporary: bool = False
    """True when ``frames_dir`` was produced by this pipeline (``.seq`` conversion)."""

    @classmethod
    def for_video(
        cls,
        paths: PathsConfig,
        video_name: str,
        frames_dir: Path,
        frames_are_temporary: bool = False,
    ) -> "RunPaths":
        return cls(
            video_name=video_name,
            frames_dir=frames_dir,
            unet_masks_dir=paths.unet_masks_dir / video_name,
            filtered_masks_dir=paths.filtered_masks_dir / video_name,
            results_dir=paths.results_dir / video_name,
            frames_are_temporary=frames_are_temporary,
        )

    def create_output_dirs(self) -> None:
        for directory in (self.unet_masks_dir, self.filtered_masks_dir, self.results_dir):
            directory.mkdir(parents=True, exist_ok=True)

    def clean(self, preserve_unet_masks: bool = False) -> None:
        """Delete this video's outputs from a previous run.

        Source frames under ``input_dir`` are never touched — only derived data
        and, when the frames were generated by us, the temporary frame folder.
        """
        log.info("Cleaning previous run data for: %s...", self.video_name)

        targets = [self.filtered_masks_dir, self.results_dir]
        if self.frames_are_temporary:
            targets.insert(0, self.frames_dir)
        if preserve_unet_masks:
            log.info("  Preserving cached U-Net masks in: %s", self.unet_masks_dir)
        else:
            targets.append(self.unet_masks_dir)

        for directory in targets:
            if directory.exists():
                shutil.rmtree(directory)
                log.info("  Removed: %s", directory)

        log.info("Directories cleaned.")


def setup_directories(paths: PathsConfig) -> None:
    """Create every top-level directory the pipeline expects."""
    log.info("Setting up directories...")
    for directory in paths.all_dirs():
        directory.mkdir(parents=True, exist_ok=True)
    log.info("All necessary directories are set up.")


def find_video_dirs(input_dir: Path) -> list[Path]:
    """Return the subfolders of ``input_dir`` that contain TIFF frames."""
    if not input_dir.exists():
        return []
    return sorted(
        d
        for d in input_dir.iterdir()
        if d.is_dir()
        and any(f.suffix.lower() in (".tif", ".tiff") for f in d.iterdir() if f.is_file())
    )


def mask_cache_is_usable(frames_dir: Path, mask_dir: Path, cache: MaskCacheConfig) -> bool:
    """Whether previously written masks can stand in for a U-Net run.

    With ``require_full_match`` the cache is only accepted when every input
    frame has a corresponding mask — a partial cache would silently drop
    detections from the frames it does not cover.
    """
    try:
        if not mask_dir.exists():
            return False

        mask_files = sorted(mask_dir.glob(cache.glob))
        if not mask_files:
            return False
        if not cache.require_full_match:
            return True

        frame_files = [
            p for p in sorted(frames_dir.iterdir())
            if p.is_file() and p.suffix.lower() in IMAGE_SUFFIXES
        ]
        if not frame_files:
            return True

        if cache.glob == "*_predict_mask.png":
            expected = {f"{p.stem}_predict_mask.png" for p in frame_files}
            missing = expected - {p.name for p in mask_files}
            if missing:
                log.info(
                    "GT cache: Found %d masks in %s, but missing %d expected masks. Will run U-Net.",
                    len(mask_files), mask_dir, len(missing),
                )
                return False
            return True

        if len(mask_files) < len(frame_files):
            log.info(
                "GT cache: Found %d masks in %s, but expected at least %d. Will run U-Net.",
                len(mask_files), mask_dir, len(frame_files),
            )
            return False

        return True

    except OSError as exc:
        log.warning("GT cache: Error while checking cached masks (%s): %s. Will run U-Net.", mask_dir, exc)
        return False


__all__ = [
    "RunPaths",
    "find_video_dirs",
    "list_frames",
    "mask_cache_is_usable",
    "setup_directories",
]
